import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import { useQuery, useMutation } from 'convex/react'
import { api } from '../../../convex/_generated/api'
import TeamPanel from './TeamPanel'
import SoccerField from './SoccerField'
import BalanceIndicator from './BalanceIndicator'
import SuplentesPanel from './SuplentesPanel'
import HinchadaPanel from './HinchadaPanel'
import AssignPlayerModal from './AssignPlayerModal'
import JoinMatchModal from '../player/JoinMatchModal'
import PlayerInfoModal from '../player/PlayerInfoModal'
import { generateBalancedTeams, calculateTeamStats } from '../../utils/teamBalancer'

function TeamBuilderStep({ match, onRegisterAddPlayerHandler }) {
  const hasAutoGenerated = useRef(false)
  
  // Modal states
  const [showAssignModal, setShowAssignModal] = useState(false)
  const [showJoinModal, setShowJoinModal] = useState(false)
  const [joinModalPlayerOnly, setJoinModalPlayerOnly] = useState(false)
  const [joinTargetTeam, setJoinTargetTeam] = useState(null) // Track which team the empty slot was clicked on
  const [showPlayerInfo, setShowPlayerInfo] = useState(false)
  const [selectedPlayer, setSelectedPlayer] = useState(null)
  const [selectedRegistration, setSelectedRegistration] = useState(null)
  const [showAutoConfirm, setShowAutoConfirm] = useState(false)
  
  // Convex queries
  const teamConfigData = useQuery(api.teamConfigurations.getByMatch, { matchId: match._id })
  const registrationsData = useQuery(api.registrations.listByMatch, { matchId: match._id })
  const playersData = useQuery(api.players.list)
  
  // Convex mutations
  const saveTeamConfig = useMutation(api.teamConfigurations.save)
  const getOrCreateTeamConfig = useMutation(api.teamConfigurations.getOrCreate)
  const removeRegistration = useMutation(api.registrations.remove)
  const createRegistration = useMutation(api.registrations.create)
  
  // Convert players array to object for easy lookup
  const players = useMemo(() => {
    if (!playersData) return {}
    return playersData.reduce((acc, player) => {
      acc[player._id] = player
      return acc
    }, {})
  }, [playersData])
  
  // Filter registrations that will attend
  const registrations = useMemo(() => {
    if (!registrationsData) return []
    return registrationsData.filter(r => r.asistira)
  }, [registrationsData])
  
  // Use teamConfig from query or create default
  const [localTeamConfig, setLocalTeamConfig] = useState(null)
  
  const teamConfig = teamConfigData || localTeamConfig
  
  // Reset modal states and auto-generate flag when match changes
  useEffect(() => {
    setShowJoinModal(false)
    setShowAssignModal(false)
    setShowPlayerInfo(false)
    hasAutoGenerated.current = false
    setLocalTeamConfig(null)
  }, [match._id])
  
  // Initialize team config if it doesn't exist
  useEffect(() => {
    const initConfig = async () => {
      if (teamConfigData === null && !localTeamConfig) {
        const config = await getOrCreateTeamConfig({ matchId: match._id })
        setLocalTeamConfig(config)
      }
    }
    initConfig()
  }, [teamConfigData, localTeamConfig, getOrCreateTeamConfig, match._id])
  
  // Auto-generate teams on first load if no assignments exist
  useEffect(() => {
    const autoGenerate = async () => {
      if (!teamConfig || !registrations.length || !Object.keys(players).length) return
      
      // Filter only jugadores (not suplentes or hinchada) - also include undefined/null tipoInscripcion as jugador
      const jugadorRegs = registrations.filter(r => 
        r.tipoInscripcion === 'jugador' || r.tipoInscripcion === undefined || r.tipoInscripcion === null
      )
      
      // Only auto-generate if there are no existing assignments and we have players
      if (!hasAutoGenerated.current && teamConfig.asignaciones.length === 0 && jugadorRegs.length > 0) {
        const playerList = jugadorRegs.map(r => players[r.jugadorId]).filter(Boolean)
        if (playerList.length > 0) {
          try {
            const assignments = generateBalancedTeams(playerList, jugadorRegs, match.jugadoresPorEquipo)
            
            await saveTeamConfig({
              partidoId: match._id,
              asignaciones: assignments
            })
            // Only mark as generated after successful save
            hasAutoGenerated.current = true
          } catch (err) {
            console.error('Error auto-generating teams:', err)
            // Don't mark as generated so it can retry
          }
        }
      }
    }
    autoGenerate()
  }, [teamConfig, registrations, players, match.jugadoresPorEquipo, match._id, saveTeamConfig])
  
  // Get assignment for a player
  const getAssignment = (playerId) => {
    return teamConfig?.asignaciones?.find(a => a.jugadorId === playerId)
  }
  
  // Handle team name change
  const handleTeamNameChange = async (team, newName) => {
    await saveTeamConfig({
      partidoId: match._id,
      [team === 'blanco' ? 'nombreEquipoBlanco' : 'nombreEquipoOscuro']: newName
    })
  }
  
  // Handle player assignment
  const handleAssignPlayer = async (playerId, team, role) => {
    const existingAssignments = teamConfig.asignaciones.filter(a => a.jugadorId !== playerId)
    
    // Calculate position based on role and existing players
    const teamAssignments = existingAssignments.filter(a => a.equipo === team)
    const roleCount = teamAssignments.filter(a => a.rol === role).length
    
    const position = getDefaultPosition(role, team, roleCount)
    
    const newAssignment = {
      jugadorId: playerId,
      equipo: team,
      rol: role,
      coordenadaX: position.x,
      coordenadaY: position.y
    }
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: [...existingAssignments, newAssignment]
    })
    
    setShowAssignModal(false)
    setSelectedPlayer(null)
  }
  
  // Handle removing player from team - with suplente promotion
  const handleUnassignPlayer = async (playerId) => {
    // Get the team the player was on
    const removedAssignment = teamConfig.asignaciones.find(a => a.jugadorId === playerId)
    const removedTeam = removedAssignment?.equipo
    
    // Remove player from assignments
    let newAssignments = teamConfig.asignaciones.filter(a => a.jugadorId !== playerId)
    
    // Remove player's registration from the match entirely
    await removeRegistration({ matchId: match._id, playerId })
    
    // Check if there are suplentes to promote
    const suplentes = registrations
      .filter(r => r.tipoInscripcion === 'suplente')
      .sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp))
    
    if (suplentes.length > 0) {
      const firstSuplente = suplentes[0]
      
      // Promote suplente to jugador (update registration)
      await createRegistration({
        partidoId: match._id,
        jugadorId: firstSuplente.jugadorId,
        estadoFisico: firstSuplente.estadoFisico,
        confirmado: true,
        asistira: true
      })
      
      // Assign to the team that had the player removed (or the one with fewer players)
      const blancoCount = newAssignments.filter(a => a.equipo === 'blanco').length
      const oscuroCount = newAssignments.filter(a => a.equipo === 'oscuro').length
      
      let targetTeam = removedTeam || (blancoCount <= oscuroCount ? 'blanco' : 'oscuro')
      
      // Get default role based on player preference
      const suplePlayer = players[firstSuplente.jugadorId]
      const preferredPosition = suplePlayer?.perfilPermanente?.posicionPreferida || 'Mediocampista'
      const roleMap = {
        'Arquero': 'arquero',
        'Defensor': 'defensor',
        'Mediocampista': 'medio',
        'Delantero': 'delantero'
      }
      const role = roleMap[preferredPosition] || 'medio'
      
      const teamAssignments = newAssignments.filter(a => a.equipo === targetTeam)
      const roleCount = teamAssignments.filter(a => a.rol === role).length
      const position = getDefaultPosition(role, targetTeam, roleCount)
      
      const newAssignment = {
        jugadorId: firstSuplente.jugadorId,
        equipo: targetTeam,
        rol: role,
        coordenadaX: position.x,
        coordenadaY: position.y
      }
      
      newAssignments = [...newAssignments, newAssignment]
    }
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: newAssignments
    })
  }
  
  // Handle promoting a suplente manually
  const handlePromoteSuplente = async (playerId) => {
    const suplenteReg = registrations.find(r => r.jugadorId === playerId && r.tipoInscripcion === 'suplente')
    if (!suplenteReg) return
    
    // Promote to jugador (update registration)
    await createRegistration({
      partidoId: match._id,
      jugadorId: playerId,
      estadoFisico: suplenteReg.estadoFisico,
      confirmado: true,
      asistira: true
    })
    
    // Assign to team with fewer players
    const blancoCount = teamConfig.asignaciones.filter(a => a.equipo === 'blanco').length
    const oscuroCount = teamConfig.asignaciones.filter(a => a.equipo === 'oscuro').length
    const targetTeam = blancoCount <= oscuroCount ? 'blanco' : 'oscuro'
    
    const player = players[playerId]
    const preferredPosition = player?.perfilPermanente?.posicionPreferida || 'Mediocampista'
    const roleMap = {
      'Arquero': 'arquero',
      'Defensor': 'defensor',
      'Mediocampista': 'medio',
      'Delantero': 'delantero'
    }
    const role = roleMap[preferredPosition] || 'medio'
    
    const teamAssignments = teamConfig.asignaciones.filter(a => a.equipo === targetTeam)
    const roleCount = teamAssignments.filter(a => a.rol === role).length
    const position = getDefaultPosition(role, targetTeam, roleCount)
    
    const newAssignment = {
      jugadorId: playerId,
      equipo: targetTeam,
      rol: role,
      coordenadaX: position.x,
      coordenadaY: position.y
    }
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: [...teamConfig.asignaciones, newAssignment]
    })
  }
  
  // Handle player position change (drag & drop)
  const handlePositionChange = async (playerId, x, y) => {
    const updatedAssignments = teamConfig.asignaciones.map(a => {
      if (a.jugadorId === playerId) {
        return { ...a, coordenadaX: x, coordenadaY: y }
      }
      return a
    })
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: updatedAssignments
    })
  }
  
  // Handle auto-generate teams (kept for future use)
  const handleAutoGenerate = async () => {
    const jugadorRegs = registrations.filter(r => 
      r.tipoInscripcion === 'jugador' || r.tipoInscripcion === undefined || r.tipoInscripcion === null
    )
    const playerList = jugadorRegs.map(r => players[r.jugadorId]).filter(Boolean)
    const assignments = generateBalancedTeams(playerList, jugadorRegs, match.jugadoresPorEquipo)
    
    await saveTeamConfig({
      partidoId: match._id,
      asignaciones: assignments
    })
    
    setShowAutoConfirm(false)
  }
  
  // Open assign modal for a player
  const handleOpenAssign = (player) => {
    const playerId = player._id || player.id
    const reg = registrations.find(r => r.jugadorId === playerId)
    setSelectedPlayer(player)
    setSelectedRegistration(reg)
    setShowAssignModal(true)
  }
  
  // Open player info modal
  const handleViewPlayerInfo = (player) => {
    const playerId = player._id || player.id
    const reg = registrations.find(r => r.jugadorId === playerId)
    setSelectedPlayer(player)
    setSelectedRegistration(reg)
    setShowPlayerInfo(true)
  }
  
  // Handle new player joined - auto-assign to target team if specified
  const handlePlayerJoined = async (newPlayerId) => {
    // If we have a target team from clicking an empty slot, auto-assign the player
    if (joinTargetTeam && newPlayerId && teamConfig) {
      // Try to get player info from cache, but don't depend on it
      const newPlayer = players[newPlayerId]
      
      // Get role - use player preference if available, otherwise default to 'medio'
      let role = 'medio'
      if (newPlayer?.perfilPermanente?.posicionPreferida) {
        const roleMap = {
          'Arquero': 'arquero',
          'Defensor': 'defensor',
          'Mediocampista': 'medio',
          'Delantero': 'delantero'
        }
        role = roleMap[newPlayer.perfilPermanente.posicionPreferida] || 'medio'
      }
      
      // Calculate position
      const teamAssignments = teamConfig.asignaciones.filter(a => a.equipo === joinTargetTeam)
      const roleCount = teamAssignments.filter(a => a.rol === role).length
      const position = getDefaultPosition(role, joinTargetTeam, roleCount)
      
      const newAssignment = {
        jugadorId: newPlayerId,
        equipo: joinTargetTeam,
        rol: role,
        coordenadaX: position.x,
        coordenadaY: position.y
      }
      
      try {
        await saveTeamConfig({
          partidoId: match._id,
          asignaciones: [...teamConfig.asignaciones, newAssignment]
        })
      } catch (err) {
        console.error('Error assigning player to team:', err)
      }
    }
    
    // Reset target team
    setJoinTargetTeam(null)
    
    // Data will auto-refresh via Convex
  }
  
  // Open join modal for empty slot (player only) - receives target team
  const handleOpenJoinFromEmptySlot = useCallback((targetTeam) => {
    setJoinTargetTeam(targetTeam)
    setJoinModalPlayerOnly(true)
    setShowJoinModal(true)
  }, [])

  // Open join modal from header (all options)
  const handleOpenJoinFromHeader = useCallback(() => {
    setJoinModalPlayerOnly(false)
    setShowJoinModal(true)
  }, [])

  // Register the add player handler for the header button
  useEffect(() => {
    if (onRegisterAddPlayerHandler) {
      onRegisterAddPlayerHandler(() => handleOpenJoinFromHeader())
    }
    
    // Cleanup: unregister handler when component unmounts
    return () => {
      if (onRegisterAddPlayerHandler) {
        onRegisterAddPlayerHandler(null)
      }
    }
  }, [onRegisterAddPlayerHandler, handleOpenJoinFromHeader])
  
  // Calculate team stats
  const teamStats = teamConfig ? calculateTeamStats(teamConfig.asignaciones, players, registrations) : null
  
  // Get suplentes and hinchada
  const suplentes = registrations.filter(r => r.tipoInscripcion === 'suplente')
  const hinchada = registrations.filter(r => r.tipoInscripcion === 'hinchada')
  
  // Get assigned players by team
  const blancoPlayers = teamConfig?.asignaciones
    ?.filter(a => a.equipo === 'blanco')
    .map(a => ({ ...a, player: players[a.jugadorId] }))
    .filter(a => a.player) || []
    
  const oscuroPlayers = teamConfig?.asignaciones
    ?.filter(a => a.equipo === 'oscuro')
    .map(a => ({ ...a, player: players[a.jugadorId] }))
    .filter(a => a.player) || []
  
  if (!teamConfig) {
    return <div className="loading">Cargando configuración...</div>
  }
  
  return (
    <div className="team-builder-step">
      <div className="team-builder-layout-new">
        {/* Left Panel - Team Blanco */}
        <TeamPanel
          team="blanco"
          teamName={teamConfig.nombreEquipoBlanco}
          players={blancoPlayers}
          registrations={registrations}
          onViewInfo={handleViewPlayerInfo}
          onUnassign={handleUnassignPlayer}
          onAddPlayer={handleOpenJoinFromEmptySlot}
          onTeamNameChange={handleTeamNameChange}
          jugadoresPorEquipo={match.jugadoresPorEquipo}
        />
        
        {/* Center - Soccer Field */}
        <div className="team-builder-center">
          <SoccerField
            teamConfig={teamConfig}
            players={players}
            registrations={registrations}
            onPositionChange={handlePositionChange}
            onPlayerClick={handleViewPlayerInfo}
          />
          
          {teamStats && (
            <BalanceIndicator
              teamStats={teamStats}
              teamConfig={teamConfig}
            />
          )}
          
          {/* Suplentes and Hinchada panels */}
          <div className="extra-panels">
            <SuplentesPanel 
              suplentes={suplentes}
              players={players}
              registrations={registrations}
              onPromote={handlePromoteSuplente}
              currentAssignments={teamConfig?.asignaciones || []}
              playersPerTeam={match.jugadoresPorEquipo}
            />
            <HinchadaPanel 
              hinchada={hinchada}
              players={players}
            />
          </div>
        </div>
        
        {/* Right Panel - Team Oscuro */}
        <TeamPanel
          team="oscuro"
          teamName={teamConfig.nombreEquipoOscuro}
          players={oscuroPlayers}
          registrations={registrations}
          onViewInfo={handleViewPlayerInfo}
          onUnassign={handleUnassignPlayer}
          onAddPlayer={handleOpenJoinFromEmptySlot}
          onTeamNameChange={handleTeamNameChange}
          jugadoresPorEquipo={match.jugadoresPorEquipo}
        />
      </div>
      
      {/* Modals */}
      <AssignPlayerModal
        isOpen={showAssignModal}
        onClose={() => {
          setShowAssignModal(false)
          setSelectedPlayer(null)
        }}
        player={selectedPlayer}
        registration={selectedRegistration}
        currentAssignment={selectedPlayer ? getAssignment(selectedPlayer._id || selectedPlayer.id) : null}
        teamConfig={teamConfig}
        playersPerTeam={match.jugadoresPorEquipo}
        onAssign={handleAssignPlayer}
        onUnassign={handleUnassignPlayer}
      />
      
      <JoinMatchModal
        isOpen={showJoinModal}
        onClose={() => setShowJoinModal(false)}
        matchId={match._id}
        match={match}
        onJoined={handlePlayerJoined}
        playerOnly={joinModalPlayerOnly}
      />
      
      <PlayerInfoModal
        isOpen={showPlayerInfo}
        onClose={() => {
          setShowPlayerInfo(false)
          setSelectedPlayer(null)
        }}
        player={selectedPlayer}
        registration={selectedRegistration}
      />
      
      {/* Regenerate confirmation modal - Hidden temporarily */}
      {showAutoConfirm && (
        <div className="modal-overlay" onClick={() => setShowAutoConfirm(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Regenerar Equipos</h2>
            </div>
            <div className="modal-body">
              <p>
                ¿Quieres regenerar los equipos automáticamente? 
                Esto reemplazará los cambios que hayas hecho.
              </p>
              <p className="text-muted mt-md">
                El algoritmo balanceará los equipos según el nivel y estado físico de cada jugador.
              </p>
            </div>
            <div className="modal-footer">
              <button 
                className="btn btn-secondary"
                onClick={() => setShowAutoConfirm(false)}
              >
                Cancelar
              </button>
              <button 
                className="btn btn-primary"
                onClick={handleAutoGenerate}
              >
                Regenerar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// Helper function to get default position
function getDefaultPosition(role, team, index) {
  const isBlanco = team === 'blanco'
  const baseY = isBlanco ? 25 : 75
  
  const positions = {
    arquero: { x: 50, y: isBlanco ? 8 : 92 },
    defensor: [
      { x: 20, y: baseY - 10 },
      { x: 40, y: baseY - 10 },
      { x: 60, y: baseY - 10 },
      { x: 80, y: baseY - 10 },
    ],
    medio: [
      { x: 25, y: baseY },
      { x: 50, y: baseY },
      { x: 75, y: baseY },
    ],
    delantero: [
      { x: 30, y: baseY + 12 },
      { x: 50, y: baseY + 15 },
      { x: 70, y: baseY + 12 },
    ]
  }
  
  if (role === 'arquero') {
    return positions.arquero
  }
  
  const rolePositions = positions[role] || positions.medio
  return rolePositions[index % rolePositions.length]
}

export default TeamBuilderStep
