import { useState, useEffect, useCallback, useRef } from 'react'
import TeamPanel from './TeamPanel'
import SoccerField from './SoccerField'
import BalanceIndicator from './BalanceIndicator'
import SuplentesPanel from './SuplentesPanel'
import HinchadaPanel from './HinchadaPanel'
import AssignPlayerModal from './AssignPlayerModal'
import JoinMatchModal from '../player/JoinMatchModal'
import PlayerInfoModal from '../player/PlayerInfoModal'
import { Storage } from '../../utils/storage'
import { generateBalancedTeams, calculateTeamStats } from '../../utils/teamBalancer'

function TeamBuilderStep({ match, onBack, onRegisterAddPlayerHandler }) {
  const [teamConfig, setTeamConfig] = useState(null)
  const [registrations, setRegistrations] = useState([])
  const [players, setPlayers] = useState({})
  const hasAutoGenerated = useRef(false)
  
  // Modal states
  const [showAssignModal, setShowAssignModal] = useState(false)
  const [showJoinModal, setShowJoinModal] = useState(false)
  const [joinModalPlayerOnly, setJoinModalPlayerOnly] = useState(false)
  const [joinTargetTeam, setJoinTargetTeam] = useState(null) // Track which team the empty slot was clicked on
  const [showPlayerInfo, setShowPlayerInfo] = useState(false)
  const [selectedPlayer, setSelectedPlayer] = useState(null)
  const [selectedRegistration, setSelectedRegistration] = useState(null)
  const [showAutoConfirm, setShowAutoConfirm] = useState(false)
  
  // Load data
  const loadData = useCallback(() => {
    const config = Storage.getOrCreateTeamConfig(match.id)
    setTeamConfig(config)
    
    const regs = Storage.getRegistrations(match.id).filter(r => r.asistira)
    setRegistrations(regs)
    
    const allPlayers = Storage.getPlayers()
    setPlayers(allPlayers)
    
    return { config, regs, allPlayers }
  }, [match.id])
  
  // Reset modal states when component mounts
  useEffect(() => {
    setShowJoinModal(false)
    setShowAssignModal(false)
    setShowPlayerInfo(false)
  }, [match.id])
  
  // Auto-generate teams on first load if no assignments exist
  useEffect(() => {
    const { config, regs, allPlayers } = loadData()
    
    // Filter only jugadores (not suplentes or hinchada)
    const jugadorRegs = regs.filter(r => r.tipoInscripcion !== 'suplente' && r.tipoInscripcion !== 'hinchada')
    
    // Only auto-generate once and if there are no existing assignments
    if (!hasAutoGenerated.current && config.asignaciones.length === 0 && jugadorRegs.length > 0) {
      hasAutoGenerated.current = true
      
      const playerList = jugadorRegs.map(r => allPlayers[r.jugadorId]).filter(Boolean)
      if (playerList.length > 0) {
        const assignments = generateBalancedTeams(playerList, jugadorRegs, match.jugadoresPorEquipo)
        
        const updatedConfig = {
          ...config,
          asignaciones: assignments
        }
        
        setTeamConfig(updatedConfig)
        Storage.saveTeamConfig(updatedConfig)
      }
    }
  }, [loadData, match.jugadoresPorEquipo])
  
  // Get assignment for a player
  const getAssignment = (playerId) => {
    return teamConfig?.asignaciones?.find(a => a.jugadorId === playerId)
  }
  
  // Handle team name change
  const handleTeamNameChange = (team, newName) => {
    const updatedConfig = {
      ...teamConfig,
      [team === 'blanco' ? 'nombreEquipoBlanco' : 'nombreEquipoOscuro']: newName
    }
    setTeamConfig(updatedConfig)
    Storage.saveTeamConfig(updatedConfig)
  }
  
  // Handle player assignment
  const handleAssignPlayer = (playerId, team, role) => {
    const existingAssignments = teamConfig.asignaciones.filter(a => a.jugadorId !== playerId)
    
    // Calculate position based on role and existing players
    const teamAssignments = existingAssignments.filter(a => a.equipo === team)
    const roleCount = teamAssignments.filter(a => a.rol === role).length
    
    const position = getDefaultPosition(role, team, roleCount)
    
    const newAssignment = {
      jugadorId: playerId,
      equipo: team,
      rol: role,
      coordenadaX: position.x,
      coordenadaY: position.y
    }
    
    const updatedConfig = {
      ...teamConfig,
      asignaciones: [...existingAssignments, newAssignment]
    }
    
    setTeamConfig(updatedConfig)
    Storage.saveTeamConfig(updatedConfig)
    setShowAssignModal(false)
    setSelectedPlayer(null)
  }
  
  // Handle removing player from team - with suplente promotion
  const handleUnassignPlayer = (playerId) => {
    // Get the team the player was on
    const removedAssignment = teamConfig.asignaciones.find(a => a.jugadorId === playerId)
    const removedTeam = removedAssignment?.equipo
    
    // Remove player from assignments
    const newAssignments = teamConfig.asignaciones.filter(a => a.jugadorId !== playerId)
    
    // Remove player's registration from the match entirely
    Storage.deleteRegistration(match.id, playerId)
    
    // Check if there are suplentes to promote
    const suplentes = registrations
      .filter(r => r.tipoInscripcion === 'suplente')
      .sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp))
    
    if (suplentes.length > 0) {
      const firstSuplente = suplentes[0]
      
      // Promote suplente to jugador
      const updatedReg = {
        ...firstSuplente,
        tipoInscripcion: 'jugador'
      }
      Storage.saveRegistration(updatedReg)
      
      // Assign to the team that had the player removed (or the one with fewer players)
      const blancoCount = newAssignments.filter(a => a.equipo === 'blanco').length
      const oscuroCount = newAssignments.filter(a => a.equipo === 'oscuro').length
      
      let targetTeam = removedTeam || (blancoCount <= oscuroCount ? 'blanco' : 'oscuro')
      
      // Get default role based on player preference
      const suplePlayer = players[firstSuplente.jugadorId]
      const preferredPosition = suplePlayer?.perfilPermanente?.posicionPreferida || 'Mediocampista'
      const roleMap = {
        'Arquero': 'arquero',
        'Defensor': 'defensor',
        'Mediocampista': 'medio',
        'Delantero': 'delantero'
      }
      const role = roleMap[preferredPosition] || 'medio'
      
      const teamAssignments = newAssignments.filter(a => a.equipo === targetTeam)
      const roleCount = teamAssignments.filter(a => a.rol === role).length
      const position = getDefaultPosition(role, targetTeam, roleCount)
      
      const newAssignment = {
        jugadorId: firstSuplente.jugadorId,
        equipo: targetTeam,
        rol: role,
        coordenadaX: position.x,
        coordenadaY: position.y
      }
      
      newAssignments.push(newAssignment)
    }
    
    const updatedConfig = {
      ...teamConfig,
      asignaciones: newAssignments
    }
    
    setTeamConfig(updatedConfig)
    Storage.saveTeamConfig(updatedConfig)
    
    // Reload data to get updated registrations
    loadData()
  }
  
  // Handle promoting a suplente manually
  const handlePromoteSuplente = (playerId) => {
    const suplenteReg = registrations.find(r => r.jugadorId === playerId && r.tipoInscripcion === 'suplente')
    if (!suplenteReg) return
    
    // Promote to jugador
    const updatedReg = {
      ...suplenteReg,
      tipoInscripcion: 'jugador'
    }
    Storage.saveRegistration(updatedReg)
    
    // Assign to team with fewer players
    const blancoCount = teamConfig.asignaciones.filter(a => a.equipo === 'blanco').length
    const oscuroCount = teamConfig.asignaciones.filter(a => a.equipo === 'oscuro').length
    const targetTeam = blancoCount <= oscuroCount ? 'blanco' : 'oscuro'
    
    const player = players[playerId]
    const preferredPosition = player?.perfilPermanente?.posicionPreferida || 'Mediocampista'
    const roleMap = {
      'Arquero': 'arquero',
      'Defensor': 'defensor',
      'Mediocampista': 'medio',
      'Delantero': 'delantero'
    }
    const role = roleMap[preferredPosition] || 'medio'
    
    const teamAssignments = teamConfig.asignaciones.filter(a => a.equipo === targetTeam)
    const roleCount = teamAssignments.filter(a => a.rol === role).length
    const position = getDefaultPosition(role, targetTeam, roleCount)
    
    const newAssignment = {
      jugadorId: playerId,
      equipo: targetTeam,
      rol: role,
      coordenadaX: position.x,
      coordenadaY: position.y
    }
    
    const updatedConfig = {
      ...teamConfig,
      asignaciones: [...teamConfig.asignaciones, newAssignment]
    }
    
    setTeamConfig(updatedConfig)
    Storage.saveTeamConfig(updatedConfig)
    loadData()
  }
  
  // Handle player position change (drag & drop)
  const handlePositionChange = (playerId, x, y) => {
    const updatedAssignments = teamConfig.asignaciones.map(a => {
      if (a.jugadorId === playerId) {
        return { ...a, coordenadaX: x, coordenadaY: y }
      }
      return a
    })
    
    const updatedConfig = {
      ...teamConfig,
      asignaciones: updatedAssignments
    }
    
    setTeamConfig(updatedConfig)
    Storage.saveTeamConfig(updatedConfig)
  }
  
  // Handle auto-generate teams (kept for future use)
  const handleAutoGenerate = () => {
    const jugadorRegs = registrations.filter(r => r.tipoInscripcion !== 'suplente' && r.tipoInscripcion !== 'hinchada')
    const playerList = jugadorRegs.map(r => players[r.jugadorId]).filter(Boolean)
    const assignments = generateBalancedTeams(playerList, jugadorRegs, match.jugadoresPorEquipo)
    
    const updatedConfig = {
      ...teamConfig,
      asignaciones: assignments
    }
    
    setTeamConfig(updatedConfig)
    Storage.saveTeamConfig(updatedConfig)
    setShowAutoConfirm(false)
  }
  
  // Open assign modal for a player
  const handleOpenAssign = (player) => {
    const reg = registrations.find(r => r.jugadorId === player.id)
    setSelectedPlayer(player)
    setSelectedRegistration(reg)
    setShowAssignModal(true)
  }
  
  // Open player info modal
  const handleViewPlayerInfo = (player) => {
    const reg = registrations.find(r => r.jugadorId === player.id)
    setSelectedPlayer(player)
    setSelectedRegistration(reg)
    setShowPlayerInfo(true)
  }
  
  // Handle new player joined - auto-assign to target team if specified
  const handlePlayerJoined = (newPlayerId) => {
    const { config } = loadData()
    
    // If we have a target team from clicking an empty slot, auto-assign the player
    if (joinTargetTeam && newPlayerId) {
      // Get the new player's info
      const allPlayers = Storage.getPlayers()
      const newPlayer = allPlayers[newPlayerId]
      
      if (newPlayer) {
        // Get default role based on player preference
        const preferredPosition = newPlayer?.perfilPermanente?.posicionPreferida || 'Mediocampista'
        const roleMap = {
          'Arquero': 'arquero',
          'Defensor': 'defensor',
          'Mediocampista': 'medio',
          'Delantero': 'delantero'
        }
        const role = roleMap[preferredPosition] || 'medio'
        
        // Calculate position
        const teamAssignments = config.asignaciones.filter(a => a.equipo === joinTargetTeam)
        const roleCount = teamAssignments.filter(a => a.rol === role).length
        const position = getDefaultPosition(role, joinTargetTeam, roleCount)
        
        const newAssignment = {
          jugadorId: newPlayerId,
          equipo: joinTargetTeam,
          rol: role,
          coordenadaX: position.x,
          coordenadaY: position.y
        }
        
        const updatedConfig = {
          ...config,
          asignaciones: [...config.asignaciones, newAssignment]
        }
        
        setTeamConfig(updatedConfig)
        Storage.saveTeamConfig(updatedConfig)
      }
    }
    
    // Reset target team
    setJoinTargetTeam(null)
    
    // Reload data to refresh UI
    loadData()
  }
  
  // Open join modal for empty slot (player only) - receives target team
  const handleOpenJoinFromEmptySlot = useCallback((targetTeam) => {
    setJoinTargetTeam(targetTeam)
    setJoinModalPlayerOnly(true)
    setShowJoinModal(true)
  }, [])

  // Open join modal from header (all options)
  const handleOpenJoinFromHeader = useCallback(() => {
    setJoinModalPlayerOnly(false)
    setShowJoinModal(true)
  }, [])

  // Register the add player handler for the header button
  useEffect(() => {
    if (onRegisterAddPlayerHandler) {
      onRegisterAddPlayerHandler(() => handleOpenJoinFromHeader())
    }
    
    // Cleanup: unregister handler when component unmounts
    return () => {
      if (onRegisterAddPlayerHandler) {
        onRegisterAddPlayerHandler(null)
      }
    }
  }, [onRegisterAddPlayerHandler, handleOpenJoinFromHeader])
  
  // Calculate team stats
  const teamStats = teamConfig ? calculateTeamStats(teamConfig.asignaciones, players, registrations) : null
  
  // Get suplentes and hinchada
  const suplentes = registrations.filter(r => r.tipoInscripcion === 'suplente')
  const hinchada = registrations.filter(r => r.tipoInscripcion === 'hinchada')
  
  // Get assigned players by team
  const blancoPlayers = teamConfig?.asignaciones
    ?.filter(a => a.equipo === 'blanco')
    .map(a => ({ ...a, player: players[a.jugadorId] }))
    .filter(a => a.player) || []
    
  const oscuroPlayers = teamConfig?.asignaciones
    ?.filter(a => a.equipo === 'oscuro')
    .map(a => ({ ...a, player: players[a.jugadorId] }))
    .filter(a => a.player) || []
  
  if (!teamConfig) {
    return <div className="loading">Cargando configuración...</div>
  }
  
  return (
    <div className="team-builder-step">
      <div className="team-builder-layout-new">
        {/* Left Panel - Team Blanco */}
        <TeamPanel
          team="blanco"
          teamName={teamConfig.nombreEquipoBlanco}
          players={blancoPlayers}
          registrations={registrations}
          onViewInfo={handleViewPlayerInfo}
          onUnassign={handleUnassignPlayer}
          onAddPlayer={handleOpenJoinFromEmptySlot}
          onTeamNameChange={handleTeamNameChange}
          jugadoresPorEquipo={match.jugadoresPorEquipo}
        />
        
        {/* Center - Soccer Field */}
        <div className="team-builder-center">
          <SoccerField
            teamConfig={teamConfig}
            players={players}
            registrations={registrations}
            onPositionChange={handlePositionChange}
            onPlayerClick={handleViewPlayerInfo}
          />
          
          {teamStats && (
            <BalanceIndicator
              teamStats={teamStats}
              teamConfig={teamConfig}
            />
          )}
          
          {/* Suplentes and Hinchada panels */}
          <div className="extra-panels">
            <SuplentesPanel 
              suplentes={suplentes}
              players={players}
              registrations={registrations}
              onPromote={handlePromoteSuplente}
              currentAssignments={teamConfig?.asignaciones || []}
              playersPerTeam={match.jugadoresPorEquipo}
            />
            <HinchadaPanel 
              hinchada={hinchada}
              players={players}
            />
          </div>
        </div>
        
        {/* Right Panel - Team Oscuro */}
        <TeamPanel
          team="oscuro"
          teamName={teamConfig.nombreEquipoOscuro}
          players={oscuroPlayers}
          registrations={registrations}
          onViewInfo={handleViewPlayerInfo}
          onUnassign={handleUnassignPlayer}
          onAddPlayer={handleOpenJoinFromEmptySlot}
          onTeamNameChange={handleTeamNameChange}
          jugadoresPorEquipo={match.jugadoresPorEquipo}
        />
      </div>
      
      {/* Modals */}
      <AssignPlayerModal
        isOpen={showAssignModal}
        onClose={() => {
          setShowAssignModal(false)
          setSelectedPlayer(null)
        }}
        player={selectedPlayer}
        registration={selectedRegistration}
        currentAssignment={selectedPlayer ? getAssignment(selectedPlayer.id) : null}
        teamConfig={teamConfig}
        playersPerTeam={match.jugadoresPorEquipo}
        onAssign={handleAssignPlayer}
        onUnassign={handleUnassignPlayer}
      />
      
      <JoinMatchModal
        isOpen={showJoinModal}
        onClose={() => setShowJoinModal(false)}
        matchId={match.id}
        match={match}
        onJoined={handlePlayerJoined}
        playerOnly={joinModalPlayerOnly}
      />
      
      <PlayerInfoModal
        isOpen={showPlayerInfo}
        onClose={() => {
          setShowPlayerInfo(false)
          setSelectedPlayer(null)
        }}
        player={selectedPlayer}
        registration={selectedRegistration}
      />
      
      {/* Regenerate confirmation modal - Hidden temporarily */}
      {showAutoConfirm && (
        <div className="modal-overlay" onClick={() => setShowAutoConfirm(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Regenerar Equipos</h2>
            </div>
            <div className="modal-body">
              <p>
                ¿Quieres regenerar los equipos automáticamente? 
                Esto reemplazará los cambios que hayas hecho.
              </p>
              <p className="text-muted mt-md">
                El algoritmo balanceará los equipos según el nivel y estado físico de cada jugador.
              </p>
            </div>
            <div className="modal-footer">
              <button 
                className="btn btn-secondary"
                onClick={() => setShowAutoConfirm(false)}
              >
                Cancelar
              </button>
              <button 
                className="btn btn-primary"
                onClick={handleAutoGenerate}
              >
                Regenerar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// Helper function to get default position
function getDefaultPosition(role, team, index) {
  const isBlanco = team === 'blanco'
  const baseY = isBlanco ? 25 : 75
  
  const positions = {
    arquero: { x: 50, y: isBlanco ? 8 : 92 },
    defensor: [
      { x: 20, y: baseY - 10 },
      { x: 40, y: baseY - 10 },
      { x: 60, y: baseY - 10 },
      { x: 80, y: baseY - 10 },
    ],
    medio: [
      { x: 25, y: baseY },
      { x: 50, y: baseY },
      { x: 75, y: baseY },
    ],
    delantero: [
      { x: 30, y: baseY + 12 },
      { x: 50, y: baseY + 15 },
      { x: 70, y: baseY + 12 },
    ]
  }
  
  if (role === 'arquero') {
    return positions.arquero
  }
  
  const rolePositions = positions[role] || positions.medio
  return rolePositions[index % rolePositions.length]
}

export default TeamBuilderStep
